export const timeLineData = [
  {
    year: "2024 - Present",
    heading: "Senior Software Consultant",
    discription: [
      "Leading complex software projects",
      "Providing high-level consulting for clients across various industries",
      "Optimizing system architecture for improved performance and scalability",
      "Specializing in cloud solutions",
      "Focusing on performance improvements and scalable software design",
    ],
    skills: [
      { skillName: "HTML", rating: 8, class: "html" },
      { skillName: "CSS", rating: 8, class: "css" },
      { skillName: "Javascript", rating: 8, class: "javascript" },
      { skillName: "Typescript", rating: 8, class: "typescript" },
      { skillName: "Angular 18", rating: 8, class: "angular" },
      { skillName: "NPM package", rating: 8, class: "npm" },
      { skillName: "NPM", rating: 8, class: "npm" },
      { skillName: "NgRx", rating: 8, class: "ngrx" },
      { skillName: "RxJs", rating: 8, class: "rxjs" },
      { skillName: "MySql", rating: 8, class: "mysql" },
      { skillName: "TypeORM", rating: 8, class: "typeorm" },
      { skillName: "Github", rating: 8, class: "github" },
      { skillName: "Azure", rating: 8, class: "azure" },
      { skillName: "CI/CD", rating: 8, class: "cicd" },
    ],
  },
  {
    year: "2023 - 2024",
    heading: "Senior Software Developer",
    discription: [
      "Developed and maintained high-performance web applications",
      "Worked with cross-functional teams to ensure high-quality solution delivery",
      "Mentored junior developers",
      "Helped implement Agile best practices",
    ],
    skills: [
      { skillName: "HTML", rating: 8, class: "html" },
      { skillName: "CSS", rating: 8, class: "css" },
      { skillName: "Javascript", rating: 8, class: "javascript" },
      { skillName: "Typescript", rating: 8, class: "typescript" },
      { skillName: "NPM", rating: 8, class: "npm" },
      { skillName: "Node Js", rating: 8, class: "nodejs" },
      { skillName: "Express Js", rating: 8, class: "expressjs" },
      { skillName: "Angular 14", rating: 8, class: "angular" },
      { skillName: "NgRx", rating: 8, class: "ngrx" },
      { skillName: "RxJs", rating: 8, class: "rxjs" },
      { skillName: "MySql", rating: 8, class: "mysql" },
      { skillName: "TypeORM", rating: 8, class: "typeorm" },
      { skillName: "Github", rating: 8, class: "github" },
    ],
  },
  {
    year: "2021 - 2023",
    heading: "Mid Frontend Developer",
    discription: [
      "Focused on building dynamic and responsive user interfaces using modern JavaScript frameworks",
      "Collaborated with UI/UX designers to implement intuitive designs",
      "Worked to improve overall user experience",
    ],
    skills: [
      { skillName: "HTML", rating: 8, class: "html" },
      { skillName: "CSS", rating: 8, class: "css" },
      { skillName: "Javascript", rating: 8, class: "javascript" },
      { skillName: "Typescript", rating: 8, class: "typescript" },
      { skillName: "Angular 8", rating: 8, class: "angular" },
      { skillName: "NPM", rating: 8, class: "npm" },
      { skillName: "NgRx", rating: 8, class: "ngrx" },
      { skillName: "RxJs", rating: 8, class: "rxjs" },
      { skillName: "Github", rating: 8, class: "github" },
      { skillName: "Azure", rating: 8, class: "azure" },
    ],
  },
  {
    year: "2019-2021",
    heading: "Full Stack Developer",
    discription: [
      "Worked on both frontend and backend development, building full-featured web applications",
      "Led the development of RESTful APIs",
      "Integrated third-party services to enhance functionality",
      "Ensured smooth interaction between client and server-side components",
    ],
    skills: [
      { skillName: "HTML", rating: 8, class: "html" },
      { skillName: "CSS", rating: 8, class: "css" },
      { skillName: "Javascript", rating: 8, class: "javascript" },
      { skillName: "Typescript", rating: 8, class: "typescript" },
      { skillName: "Angular 7", rating: 8, class: "angular" },
      { skillName: "NPM", rating: 8, class: "npm" },
      { skillName: "MongoDb", rating: 8, class: "mongodb" },
      { skillName: "Mongoose", rating: 8, class: "mongoose" },
      { skillName: "Github", rating: 8, class: "github" },
    ],
  },
  {
    year: "2017 - 2019",
    heading: "Freelancing",
    discription: [
      "Worked with various clients on freelance projects, providing software development services",
      "Focused on building custom websites and web applications",
      "Assisted businesses with their technical needs and solutions",
    ],
    skills: [
      { skillName: "HTML", rating: 8, class: "html" },
      { skillName: "CSS", rating: 8, class: "css" },
      { skillName: "Javascript", rating: 8, class: "javascript" },
      { skillName: "React", rating: 8, class: "react" },
      { skillName: "Php", rating: 8, class: "php" },
      { skillName: "MongoDb", rating: 8, class: "mongodb" },
      { skillName: "MySql", rating: 8, class: "mysql" },
      { skillName: "PostgreSql", rating: 8, class: "postgresql" },
      { skillName: "Mongoose", rating: 8, class: "mongoose" },
      { skillName: "Github", rating: 8, class: "github" },
      { skillName: "Ngnix", rating: 8, class: "ngnix" },
      { skillName: "Netlify", rating: 8, class: "netlify" },
    ],
  },
  {
    year: "2014 - 2017",
    heading: "Engineering",
    discription: [
      "Pursued a Bachelor's degree in Computer Engineering",
      "Gained a strong foundation in algorithms, data structures, and computer systems",
      "Participated in various academic projects and internships",
    ],
  },
  {
    year: "2011-2014",
    heading: "Diploma",
    discription: [
      "Completed a diploma in Computer Science and Engineering",
      "Learned programming languages, computer hardware, and software engineering principles",
    ],
  },
  {
    year: "2010-2011",
    heading: "SSC",
    discription: [
      "Completed secondary school with a focus on science and mathematics",
      "Laid the foundation for a career in technology",
    ],
  },
];
